- package-lock.json
- package.json
- src/manifest-input/setupLoaderScript.ts
> Support builds in Windows OS

- package-lock.json
- package.json
Firebase 7.5.0 causes the push reloader SW to fail to register.
https://gist.github.com/jacksteamdev/4a0f11666d52a96f7609c1d274bcc852
> Revert firebase to 7.5.0

- __fixtures__/basic-paths.ts
- __fixtures__/extensions/basic/devtools/devtools.html
- __fixtures__/extensions/basic/devtools/devtools1.ts
- __fixtures__/extensions/basic/devtools/devtools2.js
- __fixtures__/extensions/basic/manifest.json
- __fixtures__/extensions/html-only/devtools/devtools.html
- __fixtures__/extensions/html-only/manifest.json
- __tests__/e2e__basic.test.ts
- src/manifest-input/__tests__/manifest__hook--options.test.ts
- src/manifest-input/manifest-parser/__tests__/manifest__unit--deriveFiles.test.ts
- src/manifest-input/manifest-parser/index.ts
@jacksteamdev 
The PR implements feature was discussed in [this issue](https://github.com/bumble-org/rollup-plugin-chrome-extension/issues/28)
Issues:
[28](https://github.com/bumble-org/rollup-plugin-chrome-extension/issues/28)
I'm new with testing so have no idea are they make sense :)
Please let me know if something is needed to be adjusted.
It has already tested as a local dependency and works fine.
If all is okay then let me know please when it can be released.
Thanks for easily extended code!
> Support for devtools_page has added. Tests have performed

- .eslintrc.js
- API.md
- README.md
- __fixtures__/utils.ts
- src/manifest-input/index.ts
- src/manifest-input/manifest-parser/combine.ts
- src/plugin-reloader-push/sw/index.ts
- src/plugin-reloader-simple/__tests__/simpleReloader__hook--generateBundle.test.ts
- src/plugin-reloader-simple/__tests__/simpleReloader__init.test.ts
- src/plugin-reloader-simple/client/background.ts
- src/plugin-reloader-simple/index.ts
- tsconfig.json
Bugfix for simple reloader where timestamp was written before bundle was fully written. Now the timestamp is written after the bundle is fully written.
> Fix simple reloader

- API.md
- README.md
- package.json
- pnpm-lock.yaml
[contributing guidelines](https://github.com/extend-chrome/.github/blob/master/CONTRIBUTING.md)
and
[code of conduct](https://github.com/extend-chrome/.github/blob/master/CODE_OF_CONDUCT.md)
Closes #33 
This PR updates the docs and package.json to reflect the migration to the new organization, `@extend-chrome`. It also removes some unused dependencies.
> Extend chrome migration

- src/plugin-reloader-simple/client/background.ts
- src/plugin-reloader-simple/client/content.ts
- src/plugin-reloader-simple/index.ts
Fixes the message logged by the simple reloader
> Fix reloader message formatting

- package.json
- pnpm-lock.yaml
and
List any relevant issue numbers: #75 
The Cheerio types are breaking the tests. Not sure if Cheerio started shipping built-in types, but they're using Template Literal Types, which requires TS 4.1.
This PR pins the Cheerio library version.
> Pin Cheerio Version

- package.json
- pnpm-lock.yaml
- src/html-inputs/__tests__/html__hook--options.test.ts
- src/html-inputs/cheerio.ts
- src/html-inputs/index.ts
This PR makes prettier a peerDependency since it was causing trouble in #91
> Remove prettier

- schema/manifest-v3.schema.json
and
Needed to use certain functions in https://developer.chrome.com/docs/extensions/reference/identity/
> Add "identity.email" as a valid permission in manifest v3

- src/manifest-input/index.ts
- src/manifest-input/updateManifest.ts
- [ x] I have read and understand the
and
- [x ] bugfix
- [ x] no
- [ x] no
> Don't change content-script file names when not wrapping

- package.json
- src/client/es/page-inline-script-loader.ts
- src/node/index.ts
- src/node/plugin-htmlAuditor.ts
This PR busts aggressively cached HTML page resources, like the devtools page.
> Bust devtools cache

- src/node/helpers.ts
- src/node/types.ts
- tests/mv3/vite-self-directive-in-csp/__snapshots__/build.test.ts.snap
- tests/mv3/vite-self-directive-in-csp/build.test.ts
- tests/mv3/vite-self-directive-in-csp/manifest-csp.json
- tests/mv3/vite-self-directive-in-csp/manifest.json
- tests/mv3/vite-self-directive-in-csp/serve.test.ts
- tests/mv3/vite-self-directive-in-csp/src/App.tsx
- tests/mv3/vite-self-directive-in-csp/src/background.ts
- tests/mv3/vite-self-directive-in-csp/src/content.ts
- tests/mv3/vite-self-directive-in-csp/src/popup.html
- tests/mv3/vite-self-directive-in-csp/src/popup.tsx
- tests/mv3/vite-self-directive-in-csp/vite.config.ts
- tests/mv3/vite-self-directive-in-csp/vite.csp.ts
- tests/runners.ts
and
List any relevant issue numbers: #279 
When the manifest.json contains the 'self' directive either in content_security_policy.extension_pages or content_security_policy.sandbox, then `vite build` fails with `Error: unable to parse manifest code`. 
After debugging for a while, I found out this is because the manifest is transformed into a file with a named default export I guess because of the single quotes needed in the CSP. This was causing the node tree to not contain a `Literal` as the `decodeManifest` …
> fix: vite build issue when using self directive in manifest.json

- packages/rollup-plugin/src/manifest-input/updateManifest.ts
> Use slash to guarantee support Windows

- .changeset/shy-lizards-protect.md
- packages/vite-plugin/src/node/plugin-fileWriter--events.ts
> fix broken `existsSync` import

- .changeset/gentle-actors-unite.md
- packages/vite-plugin/src/node/plugin-hmr.ts
> Fix isImporter recursion

- .changeset/red-bobcats-remember.md
- packages/vite-plugin/src/node/helpers.ts
> Fix manifest icons type

- .changeset/fresh-suns-do.md
- packages/vite-plugin/package.json
- pnpm-lock.yaml
> chore: move rxjs to package.deps

- .changeset/tidy-shrimps-cross.md
- packages/vite-plugin/src/node/plugin-background.ts
- packages/vite-plugin/tests/out/basic-js/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/basic-ts/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/dynamic-script/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-content-script-css-imports-2/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-content-script-css-imports-3/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-content-script-css-imports/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-declared-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-dynamic-script-resources-minify/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-dynamic-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/vite-react-fast-refresh/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/with-copied-assets/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/with-public-dir/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/out/with-web-accessible-html/__snapshots__/serve.test.ts.snap
> Hotfix background

- packages/vite-plugin/src/node/plugin-manifest.ts
Reverts crxjs/chrome-extension-tools#602
> Revert "fix: filter out vite serve plugin context"

- .changeset/perfect-doors-exercise.md
- packages/vite-plugin/src/node/fileWriter-rxjs.ts
Closes: #608. Thanks to @lionelhorn
> temporary fix for dynamic imports

- packages/rollup-plugin/README.md
- packages/rollup-plugin/__tests__/e2e__mv3-basic-js.test.ts
- packages/rollup-plugin/jest.setup.ts
- packages/rollup-plugin/src/manifest-input/convertMatchPatterns.ts
- packages/vite-plugin/src/node/plugin-manifest.ts
- packages/vite-plugin/tests/runners.ts
- schema/manifest-v2.schema.json
- schema/manifest-v3.schema.json
Fixed a few random typos (this was a trial run for [a CLI I made](https://github.com/Lioness100/rspell))
> docs: fix typos

- packages/vite-plugin/package.json
- packages/vite-plugin/tests/e2e/runners.ts
- pnpm-lock.yaml
This PR upgrades Playwright and configures e2e tests to use the new headless mode.
> upgrade playwright chromium

- packages/vite-plugin/src/node/files.ts
- packages/vite-plugin/src/node/manifest.ts
- pnpm-lock.yaml
- schema/manifest-v3.schema.json
Allows using the sidePanel API https://developer.chrome.com/docs/extensions/reference/sidePanel/
> Add Side Panel page to the html files list

- packages/rollup-plugin/schema/manifest-v3.schema.json
Updated Manifest v3 schema to include the sidePanel permission & related settings for rollup package
> added sidePanel to rollup v3 schema

- .changeset/fair-flies-admire.md
- .changeset/shaggy-glasses-design.md
Not sure why this changeset was generated
> Delete invalid changeset

- packages/vite-plugin-docs/docs/getting-started/_create-project-tabs.mdx
add info in the docs about #723
> docs: warn react users about hmr not working when using @vite/plugin-react-swc

- .changeset/unlucky-goats-exist.md
- packages/rollup-plugin/schema/manifest-v3.schema.json
See https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts#injecting-in-related-frames
> Add match_origin_as_fallback to manifest-v3.schema.json

- .changeset/empty-mugs-exist.md
- packages/vite-plugin/src/node/plugin-hmr.ts
Fixes https://github.com/crxjs/chrome-extension-tools/issues/718
> fix: monorepo hmr

- .github/workflows/release.yml
- .github/workflows/rollup-plugin.yml
- .github/workflows/vite-plugin.yml
> upgrade pnpm action setup version

- .changeset/ten-olives-build.md
- packages/vite-plugin/src/node/manifest.ts
> fixes #824

- packages/vite-plugin-docs/docs/common/ImageCodeBlock.js
- packages/vite-plugin-docs/docs/common/_get-url-for-images.mdx
- packages/vite-plugin-docs/docs/getting-started/react/02-add-content-script.md
- packages/vite-plugin-docs/docs/getting-started/solid/02-add-content-script.md
- packages/vite-plugin-docs/docs/getting-started/vanilla-js/02-add-content-script.md
- packages/vite-plugin-docs/docs/getting-started/vue/02-add-content-script.md
Add manifest instructions and specificy example when using getURL()
> Update Docs when referencing Images

- packages/rollup-plugin/schema/manifest-v3.schema.json
- schema/manifest-v3.schema.json
Add missing offscreen permission to schema.
- https://developer.chrome.com/docs/extensions/reference/api/offscreen
- https://github.com/crxjs/chrome-extension-tools/blob/main/packages/rollup-plugin/manifest.schema.json
- https://github.com/crxjs/chrome-extension-tools/pull/711
- https://github.com/crxjs/chrome-extension-tools/issues/712
> Support offscreen permissions

- packages/vite-plugin/tests/e2e/mv3-vanilla-favicon-test/manifest.json
- packages/vite-plugin/tests/e2e/mv3-vanilla-favicon-test/src/content.ts
- packages/vite-plugin/tests/e2e/mv3-vanilla-favicon-test/vite-serve.test.ts
- packages/vite-plugin/tests/e2e/mv3-vanilla-favicon-test/vite.config.ts
the subject returned to us somehow after 2,5 years https://github.com/crxjs/chrome-extension-tools/issues/1027
favicons are working - lets prove that
> tests: add favicon chrome api e2e test

- .changeset/twelve-ants-smoke.md
> chore: add missing patch

- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/background.ts
mentioned in the discord
https://discord.com/channels/1325509878139322481/1383613950511415356
> refactor(tests): remove not needed call to skipWaiting()

- packages/rollup-plugin/README.md
- packages/vite-plugin-docs/README.md
- packages/vite-plugin-docs/src/components/MaintenanceBanner/index.tsx
- packages/vite-plugin-docs/src/components/MaintenanceBanner/styles.module.css
> docs: update maintenance banner and styles

- .changeset/rotten-moles-doubt.md
- packages/vite-plugin/src/node/getMatchPatternOrigin.test.ts
- packages/vite-plugin/src/node/helpers.ts
> feat: add support for root url content script match in firefox #1056
