crxjs/chrome-extension-tools

- src/html-inputs/__tests__/html__hook--options.test.ts
- src/html-inputs/index.ts
Temporarily do not cache html parsing results
> Patch bug in html-inputs plugin

- __fixtures__/extensions/chunk-file-names/background/background.js
- __fixtures__/extensions/chunk-file-names/content/content.js
- __fixtures__/extensions/chunk-file-names/manifest.json
- __fixtures__/extensions/chunk-file-names/rollup.config.js
- __fixtures__/extensions/chunk-file-names/shared/imported.js
- __tests__/e2e__basic.test.ts
- __tests__/e2e__chunk-file-names.test.ts
- src/index.ts
- src/mixed-format/index.ts
- src/mixed-format/regenerateBundle.ts
and
List any relevant issue numbers: #60
PR #53 broke chunk file names for non-entry modules, removing subfolders and adding double hashes to output files. The manifest retains the expected file names, but the files are named incorrectly.
This PR adds tests to ensure that every file in the manifest is correctly named in the output bundle.
> [fix] output correctly named chunks

- __fixtures__/extensions/basic-ts/rollup.config.js
- __tests__/e2e__basic-ts.test.ts
- src/mixed-format/index.ts
- src/mixed-format/regenerateBundle.ts
and
List any relevant issue numbers: Fixes #69 
Source maps stopped working since 3.5.x as the sourcemap output option was no longer passed through to rollup.
> Pass output.sourcemap option through to (re)generateBundle. Fixes #69

- __fixtures__/plugin-context.ts
- src/manifest-input/__tests__/manifest__hook--generateBundle.test.ts
- src/manifest-input/index.ts
and
List any relevant issue numbers: https://github.com/extend-chrome/js-react-boilerplate/issues/2
RPCE outputs possibly invalid file paths in the manifest on Windows due to the way the `path` module behaves on Windows.
```
const path = require('path');
const string = path.join('foo', 'bar');
// Unix    => foo/bar
// Windows => foo\\bar
```
This PR maps all script paths through through [`slash`](https://www.npmjs.com/package/slash) to fix this.
> Fix manifest file paths for Windows

- src/manifest-input/browser/getDeepMatches.test.ts
- src/manifest-input/browser/getDeepMatches.ts
and
List any relevant issue numbers: #56 
`chrome.runtime.lastError` is `null` rather than `undefined`[1] in Firefox so the `getDeepMatches` caller in importWrapper--implicit.ts leads to an error being thrown.
This breaks the startup of my extension in Firefox.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1406674
> Don't call `Object.keys` on `null` in `getDeepMatches`

- src/plugin-reloader-simple/__tests__/simpleReloader__hook--writeBundle.test.ts
- src/plugin-reloader-simple/index.ts
and
List any relevant issue numbers: #85 
The simple reloader is triggering a reload before or while files are being written. This PR adds a configurable delay:
```javascript
// wait 250ms to trigger reload
simpleReloader({ reloadDelay: 250 }) 
// default delay is 100ms
simpleReloader() 
// Set delay to 0 to reload synchronously
simpleReloader({ reloadDelay: 0 })
```
> fix: delay reload by 100ms

- __fixtures__/extensions/mv2-kitchen-sink/_locales/en/messages.json
- __fixtures__/extensions/mv2-kitchen-sink/_locales/es/messages.json
- __fixtures__/extensions/mv2-kitchen-sink/manifest.json
- __fixtures__/extensions/mv2-locales/babel.config.json
- __fixtures__/extensions/mv2-locales/rollup.config.js
- __fixtures__/extensions/mv2-locales/src/_locales/en/messages.json
- __fixtures__/extensions/mv2-locales/src/_locales/es/messages.json
- __fixtures__/extensions/mv2-locales/src/background.js
- __fixtures__/extensions/mv2-locales/src/manifest.json
- __fixtures__/extensions/mv3-kitchen-sink/_locales/en/messages.json
- __fixtures__/extensions/mv3-kitchen-sink/_locales/es/messages.json
- __fixtures__/extensions/mv3-kitchen-sink/manifest.json
- __fixtures__/extensions/mv3-locales/babel.config.json
- __fixtures__/extensions/mv3-locales/rollup.config.js
- __fixtures__/extensions/mv3-locales/src/_locales/en/messages.json
- __fixtures__/extensions/mv3-locales/src/_locales/es/messages.json
- __fixtures__/extensions/mv3-locales/src/manifest.json
- __fixtures__/extensions/mv3-locales/src/service_worker.js
- __fixtures__/mv2-kitchen-sink-paths.ts
- __fixtures__/mv3-kitchen-sink-paths.ts
- __tests__/e2e__mv2-kitchen-sink.test.ts
- src/manifest-input/__tests__/manifest__hook--buildStart.test.ts
- src/manifest-input/__tests__/manifest__hook--generateBundle.test.ts
- src/manifest-input/manifest-parser/__tests__/mv2-manifest__unit--deriveFiles.test.ts
- src/manifest-input/manifest-parser/__tests__/mv3-manifest__unit--deriveFiles.test.ts
- src/manifest-input/manifest-parser/index.ts
- src/validate-names/index.ts
The PR adds support for localizing Chrome Extensions. Create your localization folder and add the `default_locales` key to your manifest. The `_locales` folder will be copied over automatically.
> Support locales

- __fixtures__/extensions/mv3-manifest-ts-array-input/rollup.config.js
- __fixtures__/extensions/mv3-manifest-ts-array-input/src/content.ts
- __fixtures__/extensions/mv3-manifest-ts-array-input/src/manifest.ts
- __fixtures__/extensions/mv3-manifest-ts-array-input/src/script.ts
- __fixtures__/extensions/mv3-manifest-ts-object-input/rollup.config.js
- __fixtures__/extensions/mv3-manifest-ts-object-input/src/content.ts
- __fixtures__/extensions/mv3-manifest-ts-object-input/src/manifest.ts
- __fixtures__/extensions/mv3-manifest-ts-object-input/src/script.ts
- __fixtures__/extensions/mv3-manifest-ts-single-input/rollup.config.js
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/App.tsx
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/content.ts
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/manifest.ts
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/popup.html
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/popup.tsx
- __fixtures__/extensions/mv3-manifest-ts-single-input/src/service_worker.ts
- __tests__/e2e__mv3-manifest-ts-array-input.test.ts
- __tests__/e2e__mv3-manifest-ts-object-input.test.ts
- __tests__/e2e__mv3-manifest-ts-single-input.test.ts
- package.json
- pnpm-lock.yaml
- src/helpers.ts
- src/index.ts
- src/manifest-input/__tests__/manifest__hook--options.test.ts
- src/manifest-input/crypto.ts
- src/manifest-input/getInputManifestPath.ts
- src/manifest-input/index.ts
- src/manifest-input/updateManifest.ts
- src/manifest-input/warnDeprecatedOptions.ts
- src/manifest-types.ts
This PR leverages `ts-node` to allow manifest files to be TS files. Type checking and environment variables are here!
```typescript
import { ManifestV3 } from 'rollup-plugin-chrome-extension'
const config: ManifestV3 = {
content_scripts: [
{
js: ['content.ts'],
matches: ['https://*/*', 'http://*/*'],
},
],
manifest_version: 3,
}
export default config
```
> Manifest as ts files

- src/manifest-input/__tests__/manifest__mv3-unit-convertMatchPatterns.ts
- src/manifest-input/convertMatchPatterns.ts
- src/manifest-input/updateManifest.ts
This PR fixes a bug that prevents Chrome from loading an extension with auto-generated web accessible resources (WAR) that support ESM content scripts. 
The MV3 WAR format includes a `matches` property that appears to be identical to the content script `matches` property. The WAR `matches` property matches the origin of a URL, not the full URL like a content script. This means that the content script matches property cannot be directly copied to WAR.
Here we're deconstructing the match pattern and pulling out the origin to recreate a valid WAR match pattern.
> Fix invalid match patterns in auto-generated web accessible resources

- src/service-worker/code-fetchHandlerForMV3HMR.ts
- test/e2e/mv3-vite-hmr-external-xhr/src/App.tsx
- test/e2e/mv3-vite-hmr-external-xhr/src/manifest.json
- test/e2e/mv3-vite-hmr-external-xhr/src/options.html
- test/e2e/mv3-vite-hmr-external-xhr/src/options.tsx
- test/e2e/mv3-vite-hmr-external-xhr/src/service_worker.ts
- test/e2e/mv3-vite-hmr-external-xhr/vite-serve.test.ts
- test/e2e/mv3-vite-hmr-external-xhr/vite.config.ts
and
https://github.com/extend-chrome/rollup-plugin-chrome-extension/pull/117#issuecomment-993002247
When using Vite with v4 of this plugin, if you have an extension or popup page that makes an external XHR request, that request gets redirected to the local server. This is because the background service worker that routes `chrome-extension://` requests to the local server so that HMR can work is routing _all_ requests, instead of just the relevant ones for HMR.
This fixes that …
> Fix external XHR requests while using Vite and HMR

- README.md
- src/index.ts
- src/service-worker/code-fetchHandlerForMV3HMR.ts
and
When the SW re-routes requests from the CRX origin to the ViteDevServer, it calls `response.text()` and makes that text the body. This causes requests to fail for some types of files, like images. This PR passes the response body directly to the new response. It should be a little more efficient too!
> Fix sw binary bug

- src/node/plugin-manifest.ts
RPCE now throws if `manifest.manifest_version !== 3`
> Enforce Manifest Version 3

- src/node/plugin-fileWriter--events.ts
- src/node/plugin-fileWriter.ts
- src/node/plugin-manifest.ts
This PR improves the way RPCE handles manifest assets, e.g., icons. A missing manifest asset causes Chrome to disable the extension.
1. If the asset is missing from the bundle, it will load the asset from the file system.
2. If the asset is missing from the file system, it will throw an ENOENT error.
The error will prevent HMR from trying to do a runtime reload until a successful build occurs, which is a nice win for DX.
> feat: auto-copy manifest assets

- src/manifest-input/updateManifest.ts
and
Eslint completed without error.
I did not include the output of prettier, because it changed other parts of the code.
Also I replicated your comment from the MV2 code path to describe what this fix does. (Use slash to guarantee support Windows)
#293
This change guarantees that only posix style path separators are present in the web_accessible_resources section of the generated manifest.json file on Windows.
> Use slash to guarantee support Windows

- .changeset/brown-panthers-hunt.md
- packages/vite-plugin/src/node/helpers.ts
I got an issue when trying to merge popup html page & another html page to use same react app entry point and control by react-router HashRouter. The error is
```
Could not resolve entry module (src/index.html#/popup)
```
I made a small change to ignore the hash part during resolving html files.
> feat: allow hash in manifest html urls

- .changeset/fair-bananas-sleep.md
- packages/vite-plugin/src/client/es/page-precontroller-script.ts
- packages/vite-plugin/tests/mv3/basic-js/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/basic-ts/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/dynamic-script/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-2/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-3/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-declared-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-dynamic-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-react-fast-refresh/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-self-directive-in-csp/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-copied-assets/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-public-dir/__snapshots__/serve.test.ts.snap
Sometimes during development, an extension page will load before the service worker has taken control of fetch, so the extension page will load the placeholder file instead of loading from the development server. When this happens, the precontroller script should reload the page at an interval, stopping after five seconds.
> Fix precontroller script

- .changeset/spotty-snails-pump.md
- packages/vite-plugin/src/client/html/precontroller.html
- packages/vite-plugin/src/node/plugin-fileWriter--pages.ts
- packages/vite-plugin/tests/mv3/basic-js/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/basic-ts/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-react-fast-refresh/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-self-directive-in-csp/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-public-dir/__snapshots__/serve.test.ts.snap
Sometimes during development, an extension page may open before the service worker has a chance to control fetch. The HTML file will load from the file system, but the script tag might load from the dev server. This PR adds a precontroller loader plugin to the dev server so that the extension page will reload and the fetch handler will get the real HTML file from the server.
> Fix precontroller script bug

- packages/vite-plugin-docs/docusaurus.config.js
Vercel deploys a preview of the docsite, but it doesn't show correctly b/c we are using a rewrite on `https://crxjs.dev` to host the docsite at `https://crxjs.dev/vite-plugin`. During production, the Docusaurus config should use `baseUrl = '/vite-plugin/`, otherwise it should use `baseUrl = '/'`.
> Fix Vercel preview deployment for docsite

- .changeset/gorgeous-eyes-add.md
- packages/vite-plugin/src/node/plugin-manifest.ts
- packages/vite-plugin/tests/mv3/basic-js/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/basic-ts/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/dynamic-script/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-2/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-3/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-declared-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-dynamic-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-react-fast-refresh/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-self-directive-in-csp/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-copied-assets/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-public-dir/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-web-accessible-html/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/testOutput.ts
Fixes #396 by merging `build.rollupOptions.input` with the explicit `optimizeDeps.entries`.
Vite ignores Rollup input if there are explicit entries. CRXJS adds manifest entries to `optimizeDeps.entries`, so Vite always ignores the Rollup inputs. This is not correct, since Rollup input is the correct place to declare extra HTML files.
This PR parses `rollupOptions.input` and adds them to `optimizeDeps.entries` alongside the manifest entries.
It also adds an output snapshot to the tests to assert that optimized deps don't change.
> Optimize rollup input

- .changeset/tame-mirrors-give.md
- packages/vite-plugin/src/node/plugin-fileWriter--chunks.ts
- packages/vite-plugin/src/node/plugin-fileWriter--polyfill.ts
- packages/vite-plugin/src/node/plugin-fileWriter--public.ts
- packages/vite-plugin/src/node/plugin-manifest.ts
I've been getting sporadic problems with `fs-extra` imports, similar to #398
This PR switches from `fs-extra` to NodeJS `fs.promises`, which fixes the problem.
> Fix fs-extra imports

- packages/vite-plugin/src/node/plugin-background.ts
- packages/vite-plugin/tests/e2e/mv3-vite-hmr-background-define/manifest.json
- packages/vite-plugin/tests/e2e/mv3-vite-hmr-background-define/src/background.ts
- packages/vite-plugin/tests/e2e/mv3-vite-hmr-background-define/src/options.html
- packages/vite-plugin/tests/e2e/mv3-vite-hmr-background-define/vite-serve.test.ts
- packages/vite-plugin/tests/e2e/mv3-vite-hmr-background-define/vite.config.ts
- packages/vite-plugin/tests/mv3/basic-js/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/basic-ts/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/dynamic-script/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-2/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports-3/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-content-script-css-imports/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-declared-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-dynamic-script-resources/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-react-fast-refresh/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/vite-self-directive-in-csp/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-copied-assets/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-public-dir/__snapshots__/serve.test.ts.snap
- packages/vite-plugin/tests/mv3/with-web-accessible-html/__snapshots__/serve.test.ts.snap
Closes #266 
The background loader wasn't loading the Vite env module, so environment variables were not loaded during dev mode.
> Fix background global constant replacement

- .changeset/late-spies-kick.md
- packages/vite-plugin/package.json
- pnpm-lock.yaml
`peerDependencies` in `package.json` didn't support `vite@>2`, so I've relaxed the peer and optional dependencies versions. I've tested it in a live project and didn't see any regressions, so I'm merging it.
Closes #451 
I spent all day trying to update the tests to support Vite 3, but couldn't get anywhere. There's a host of problems, but as far as I can tell, Vite 3 can't be run inside of Jest. Vite 3 is bundled to ESM, and Vite's CJS adaptor doesn't work in Jest. When I did get it to run, it exits without an error message.
I did try migrating to Vitest, which works the best. I like this as a future option, but Vite 3 compiles config files differently; I couldn't get aliases working, and debugging the plugin code doesn't work. Maybe we can get this working in the future...
> Fix Vite 3 peer dep error

- packages/vite-plugin-docs/docs/concepts/00-manifest.md
Example from the docs doesn't work, since `defineManifest` only accepts one parameter:
```typescript
// defineManifest.ts
export type ManifestV3Fn = (env: ConfigEnv) => ManifestV3 | Promise<ManifestV3>
```
> Fix defineManifest example in docs

- .changeset/large-dogs-kiss.md
- packages/vite-plugin/src/node/helpers.ts
- packages/vite-plugin/src/node/stubMatchPattern.test.ts
Closes #459. Allows to put `<all_urls>` in `manifest.json`. Please see issue for details.
> allow <all_urls> in matches section for web accessible resources

- .changeset/olive-walls-change.md
- packages/vite-plugin/package.json
CRXJS isn't yet fully compatible with Vite 3, see #454, #462
> CRXJS isn't fully compatible with Vite 3

- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vue/_category_.yml
This fixes #450 
Starting from Node 17, type assertions are needed to allow for json imports directly per https://github.com/tc39/proposal-import-assertions
> docs: add type assertions to json import documentation

- packages/vite-plugin-docs/docs/concepts/00-manifest.md
Example from the docs has an issue with the regex not replacing all the non digits, dots, or dash characters.
> docs: fix manifest ts example regex

- .changeset/sixty-mirrors-promise.md
- packages/vite-plugin/package.json
- pnpm-lock.yaml
I'm removing peerDeps from `package.json`. This is a Vite plugin, so OFC you're using Vite.
Also removing `package.json#engines`. CRXJS supports the minimum Node version that Vite 3 supports, so this is redundant.
> Remove peerDeps, optDeps, engines

- packages/rollup-plugin/package.json
- pnpm-lock.yaml
Renovate PR's have been failing lately b/c of a TS error about mismatched RxJS versions. This PR pins RxJS to 7.5.7, hopefully it passes CI.
> pin rxjs to 7.5.7

- .changeset/beige-snails-kiss.md
- packages/vite-plugin-docs/docs/getting-started/solid/00-create-project.md
The SolidJS templates lack the `package.json` [module declaration](https://nodejs.org/api/packages.html). This causes the Vite config file to fail to build.
> Add type module warning

- packages/vite-plugin-docs/docs/_tip-getting-started.md
- packages/vite-plugin-docs/docs/getting-started/_create-project-tabs.mdx
- packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/solid/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vanilla-js/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
Adds a Vite 3 tab to the code blocks on React, Vanilla, and Vue getting started guides.
> Vite 3 support notice

- .changeset/fluffy-numbers-brake.md
- packages/vite-plugin/src/node/plugin-contentScripts_dynamic.ts
- packages/vite-plugin/tests/out/vite-dynamic-script-resources-minify/__snapshots__/build.test.ts.snap
Addendum to #575 . The ";" character was added irrespectively of the original one. Now, if there was a "," , it is preserved.
> fix: maintain ; and , during minification

- packages/vite-plugin/src/node/plugin-manifest.ts
Fixes warning for projects configs with multiple HTML files 
Error:
Vite config:
```
rollupOptions: {
input: ["src/pages/websocket.html"],
},
```
> fix: filter out vite serve plugin context

- .changeset/stupid-years-whisper.md
- packages/vite-plugin/src/node/files.ts
Sometimes `web_accessible_resources` requires redundant match patterns:
```typescript
{
matches: ["<all_urls>"],
resources: [
"images/*",
"images/**/*",
],
}
```
This usage creates duplicates in the files list, which, in turn, causes warnings during the build.
> fix: pass war through a set to dedupe

- .changeset/gold-spies-occur.md
- packages/vite-plugin/src/node/plugin-contentScripts_dynamic.ts
Fixes #573 .
See the discussion for more details.
> fix: avoid waiting for fileReady when serving

- packages/vite-plugin/package.json
- packages/vite-plugin/src/node/plugin-contentScripts_dynamic.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/manifest.json
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/background.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/content.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/header.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/style.css
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src2/header.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src2/style.css
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/vite-serve.test.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/vite.config.ts
- pnpm-lock.yaml
Relates to #589, see https://github.com/crxjs/chrome-extension-tools/pull/589#issuecomment-1328356623
This PR adds a ViteDevServer middleware to wait for the file writer to complete all content scripts before sending an HTTP response.
There was no test coverage for HMR in dynamic content scripts, so I added a test.
> Add middleware to await file ready

- .changeset/grumpy-brooms-exist.md
- packages/vite-plugin/src/node/index.ts
Resets the contentScripts Map when the main plugin is initialized (allows Vite JS API to make multiple builds).
> fix: reset contentScripts when main plugin is initialized

- packages/vite-plugin/src/node/fileWriter.ts
- packages/vite-plugin/src/node/plugin-fileWriter.ts
Empties the outdir as soon as possible, before copy plugins might start writing files
> empty out dir before writing any files

- .changeset/eleven-buttons-dream.md
- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
Add info regarding this bug: https://github.com/crxjs/chrome-extension-tools/issues/567
> Add tip `type: module` to vue page

- .changeset/late-paws-change.md
- packages/rollup-plugin/src/manifest-input/convertMatchPatterns.ts
Currently the all_urls match pattern causes builds to fail. 
This is just a fix that was introduced for the vite plugin:
https://github.com/crxjs/chrome-extension-tools/issues/511
https://github.com/crxjs/chrome-extension-tools/pull/460
> fix all_urls

- .changeset/small-phones-beam.md
- packages/vite-plugin-docs/docs/getting-started/react/02-add-content-script.md
As React 18 no longer supports the ReactDOM.render method, its now uses ReactDOM.createRoot. So, I updated the documentation accordingly.
> Docs Update: React v18 ReactDOM.render changes

- .changeset/wicked-moose-listen.md
- packages/rollup-plugin/schema/manifest-v3.schema.json
- packages/vite-plugin/src/node/manifest.ts
- schema/manifest-v3.schema.json
The current definition of input_components is outdated. Update them to match [the official document](https://developer.chrome.com/docs/extensions/mv3/manifest/input_components/). Only v3 is updated because I cannot find v2 document anymore.
> fix: schema of input_components

- .changeset/moody-ligers-exercise.md
- packages/vite-plugin/src/node/compileFileResources.ts
In order to handle the case of a circular dependency on js chunk, 
`compileFileResources` function has been modified to return immediately in the case of processed files.
[#719](https://github.com/crxjs/chrome-extension-tools/issues/719)
> fix: infinite recursion on circular dependency

- .changeset/eleven-planes-tease.md
- packages/vite-plugin/package.json
Hi, I saw the CJS export path for the beta version of Vite plugin is broken.
> fix(package): update cjs export path

- packages/vite-plugin-docs/docs/getting-started/react/01-dev-basics.md
as [reported in the discussion here](https://github.com/crxjs/chrome-extension-tools/discussions/709) - docs section "Development Basics with React" is missing the extension installation part. It exist for other libraries
Before:
<details>
</details>
After:
<details>
</details>
> docs: add missing extension install guide for react

- .changeset/fluffy-geckos-flash.md
- packages/vite-plugin/src/node/plugin-background.ts
- packages/vite-plugin/src/node/plugin-manifest.ts
This is a follow up to https://github.com/crxjs/chrome-extension-tools/pull/776
I tried it out and the firefox build ignores background scripts, this PR fixes it
> fix: background scripts for firefox build

- packages/vite-plugin-docs/docs/getting-started/vue/02-add-content-script.md
- packages/vite-plugin-docs/docs/getting-started/vue/03-dev-content-script.md
I found that the documentation lacks information on how to use `content-script` of `vue`.
> docs: added Vue use cases

- packages/vite-plugin-docs/docs/getting-started/_create-project-tabs.mdx
- packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vanilla-js/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
Minor fix for current docs site says to create vanilla js project even for react and vue based extensions. eg [here](https://crxjs.dev/vite-plugin/getting-started/vue/create-project). I think it should say react/vue there instead of vanilla js.  so i did a minor fix to correct those. 
this required refactoring of  _create-project-tabs.mdx to a jsx style so the proejctType could be parameterized The new versions looks similar let me know if you think this might cause any issue.  
ss for new versions
thanks
> Fix: Adding correct projectType for VitePlugin docs

- .changeset/chatty-teachers-compare.md
- packages/vite-plugin/src/client/es/hmr-client-worker.ts
I was running into an issue where refreshing an extension page would load stale code.
This happened because without the cache-control header, refreshing would use the cached version of index.html. Vite already sets the header appropriately, so we just need to pass it down through the service worker.
> Proxy Cache-Control header

- .changeset/sour-teachers-learn.md
- .github/workflows/release.yml
> fix: usage of `a deprecated Node.js version` in CI

- .changeset/calm-lies-argue.md
- packages/vite-plugin/package.json
https://github.com/crxjs/chrome-extension-tools/issues/939
https://github.com/crxjs/chrome-extension-tools/issues/758
Support CommonJS. 
Under CommonJS, the old `index.cjs` configured in the project's `package.json` does not contain all methods. Modify the required configuration file to support CommonJS.
> fix: cjs require file

- .changeset/silent-cobras-jump.md
- packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vanilla-js/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
#955 
#952 
Add 
```sh
npm install --save-dev @crxjs/vite-plugin
```
as an install step for react, vanilla-js and vue
> Update vite-plugin-docs getting-started with crxjs install step

- .changeset/modern-drinks-retire.md
- .github/workflows/status-notice.yml
- README.md
- packages/rollup-plugin/README.md
- packages/vite-plugin-docs/README.md
- packages/vite-plugin-docs/docusaurus.config.js
- packages/vite-plugin-docs/src/components/MaintenanceBanner/index.tsx
- packages/vite-plugin-docs/src/components/MaintenanceBanner/styles.module.css
- packages/vite-plugin-docs/src/theme/Root.tsx
- packages/vite-plugin/README.md
This PR implements maintenance status notifications across the CRXJS project to inform users about the search for new maintainers and potential archival date.
- Added new `status-notice.yml` workflow that automatically adds maintenance notices to:
- New issues
- New pull requests
- New comments on issues
- New comments on pull requests
- Implemented duplicate detection to prevent multiple notices on the same issue/PR
- Added error handling and logging for the GitHub Actions workflow
- Added appropriate permissions for issues and pull requests
- Added maintenance notice banner to all README files:
- Root repository
- Rollup plugin package
- Vite plugin package
- Vite plugin documentation
- Repositioned root README banner for better visibility
- Added new `MaintenanceBanner` component with: …
> Add Maintenance Status Notifications

- .changeset/great-fishes-remember.md
- packages/vite-plugin/src/client/es/hmr-client-worker.ts
Fixes #909 
crxjs vite plugins client worker currently doesn't propagate headers.
https://github.com/crxjs/chrome-extension-tools/blob/a6d882a5091da474ffcfde815c53bf4eda19b6a6/packages/vite-plugin/src/client/es/hmr-client-worker.ts#L24
^ Request headers are lost immideately.
https://github.com/crxjs/chrome-extension-tools/blob/a6d882a5091da474ffcfde815c53bf4eda19b6a6/packages/vite-plugin/src/client/es/hmr-client-worker.ts#L47-L49
For some reason response headers are also omitted.
> Propagate headers in hmr-client-worker.ts/sendToServer

- RELEASES.md
This PR adds a comprehensive RELEASES.md file that documents the release process for the CRXJS project. The documentation covers the changesets workflow, details about the monorepo structure, and instructions for both contributors and maintainers.
- Create RELEASES.md with detailed documentation for:
- Repository structure overview
- Change management with Changesets
- Release process via GitHub Changeset PRs
- Current prerelease state and normalization steps
- Future release management
This documentation is especially important as the project is currently seeking new maintainers (deadline: March 31, 2025). Clear release process documentation will help onboard potential new maintainers and ensure consistent release practices during the transition period.
- Part of the transition …
> Add RELEASES.md documentation

- .changeset/blue-sheep-enjoy.md
- packages/vite-plugin/src/client/es/hmr-client-worker.ts
- packages/vite-plugin/src/node/defineClientValues.ts
- packages/vite-plugin/src/node/types.ts
Fixing HMR with latest version of the Vite (`>=6.0.9`, `>=5.4.12, <6.0.0`, `>=4.5.6, <5.0.0`) - passing web socket token.
Changes based on comment from vite dev (https://github.com/crxjs/chrome-extension-tools/issues/971#issuecomment-2608871639) -  passing `config.webSocketToken` to `hmr-client-worker.ts` under the key `__HMR_TOKEN__`.
Closes #971
> fix: make HMR working again with latest vite version

- packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md
as a consumer of the "getting started with react" vite plugin docs, it can be confusing to see references to a file in the setup process that is not yet created or available to import.
maybe we can assert that users should create the manifest file _before_ instructing them to reference a manifest file in their Vite config?
| before | after |
| ---- | --- |
| <img width="1411" alt="Screenshot 2025-05-18 at 4 10 48 PM" src="https://github.com/user-attachments/assets/800ba5d3-5bdf-408a-91e4-ca197875b81d" /> |  <img width="1411" alt="Screenshot 2025-05-18 at 4 10 24 PM" src="https://github.com/user-attachments/assets/47eb4a76-8b71-4782-8e9f-d0557b3f8651" />|
> docs(vite-plugin): reorder some docs in the Getting Started with React

- .changeset/pre.json
just ran
```
pnpm changeset pre exit
```
as the task says https://github.com/crxjs/chrome-extension-tools/issues/991
> chore: exit pre-release mode

- packages/vite-plugin-docs/docs/getting-started/_create-project-tabs.mdx
- packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/solid/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vanilla-js/00-create-project.md
- packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md
This PR addresses issue #991 by removing beta tags from the @crxjs/vite-plugin
installation instructions and cleaning up the documentation UI.
Updated all framework getting-started guides to install the stable version:
- `packages/vite-plugin-docs/docs/getting-started/react/00-create-project.md`
- `packages/vite-plugin-docs/docs/getting-started/vue/00-create-project.md`
- `packages/vite-plugin-docs/docs/getting-started/vanilla-js/00-create-project.md`
- `packages/vite-plugin-docs/docs/getting-started/solid/00-create-project.md`
**Before:**
```sh
npm install --save-dev @crxjs/vite-plugin@beta
```
**After:**
```sh
npm install --save-dev @crxjs/vite-plugin
```
Simplified the project creation flow by removing the confusing version toggle:
- …
> docs: remove beta tags and clean up Vite version UI (#991)

- packages/rollup-plugin/__tests__/e2e__mv3-playwright.test.ts
- packages/rollup-plugin/package.json
- packages/vite-plugin/package.json
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/manifest.json
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/src1/background.ts
- packages/vite-plugin/tests/e2e/mv3-vite-dynamic-content-script-hmr/vite-serve.test.ts
- packages/vite-plugin/tests/e2e/mv3-vite-vanilla-content-script-hmr/vite-serve.test.ts
- packages/vite-plugin/tests/e2e/runners.ts
- pnpm-lock.yaml
**goal**
update chrome to 136 (latest)
**problems solved**
when upgrading i've found out that the chrome 134+ wont load extensions when developer mode is not enabled. It needs to be enabled the whole time for user to load the unpacked extension, and for the cli usage --load-extension this is not required until you need to reload the extension - the tests are doing exactly that. 
two tests were failing because of this reason:
```
$env:DEBUG='crx:*';$env:TIMEOUT='999999'; pnpm run test:run:e2e tests/e2e/mv3-vite-vanilla-content-script-hmr/vite-serve.test.ts
$env:DEBUG='crx:*';$env:TIMEOUT='999999'; pnpm run test:run:e2e tests/e2e/mv3-vite-dynamic-content-script-hmr/vite-serve.test.tsclear
```
the `mv3-vite-vanilla-content-script-hmr/vite-serve.test.ts` is skipped in CI for some reason but …
> chore: update playwright-chromium (chrome 136)

- .github/workflows/rollup-plugin.yml
- .github/workflows/vite-plugin.yml
- packages/vite-plugin/src/node/index.ts
- packages/vite-plugin/src/node/plugin-print.ts
This PR modifies Vite's default terminal output.  
The original terminal output displayed a URL which is **less meaningful** and **potentially misleading** in CRXJS-based projects.  
Adjusted the default terminal output as shown below:
> feat: beautiful terminal

- packages/vite-plugin/tests/runners.ts
when debugging output tests failures it was helpful.
It is there for `serve`, but not for `build` test cases. 
Lets just add it so that we can see the intermediate results of vite transforms
> feat: make vite inspect plugin run also on `build` test cases

- .changeset/heavy-sheep-wave.md
- .github/ISSUE_TEMPLATE/config.yml
- packages/rollup-plugin/package.json
- packages/vite-plugin/package.json
Normally, GitHub tracks public projects using the `repository`, but `CRXJS` hasn't been correctly tracked (as shown below).
This is because the repository field in the original package.json incorrectly pointed to the old repository name. I've now updated the address correctly.
I believe we should immediately release a new version to trigger GitHub's tracking, including the Rollup version.
> fix: update repository url
